### ISSUE TITLE
1.18.2 fabric crash

### ISSUE THREAD

**Issue by Redd56** [astronotter/ottercraft#5]
when loading into a minecraft world in 1.18.2 ottercraft crashes, here is the [crashlog](https://pastebin.com/nPYqxpU6)

**Comment by Sunconure11** [comment]
Can confirm the same issue.

https://gist.github.com/Sunconure11/439c0b2e698232dc58b15617bacb3a8e

**Comment by astronotter** [comment]
Hi thanks for reporting the issue!

I wasn't able to reproduce the error but I suspect based on the error that it was caused by the common jar configuration which we have now moved away from, would you be able to confirm if the most recent build fixes the issue? I've posted it here: https://github.com/astronotter/ottercraft/releases/tag/v1.18.2-fabric-beta

Thanks!

**Comment by Redd56** [comment]
Give me a few hours and sure thing!

**Comment by Redd56** [comment]
just remembered ill test now

**Comment by Redd56** [comment]
well no crash ill test in game now
yep all is well. i think its ready to push as a release

**Comment by astronotter** [comment]
Awesome, thanks so much for taking a look!

**Comment by Sunconure11** [comment]
Did this build ever get pushed out? Or are there other issues you need to deal with?

**Comment by astronotter** [comment]
Hi @Sunconure11 sorry for the delay, the latest build is now pushed out on CF, and there is a release on here too.
